name: geowake2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  # For Flutter 3.7 or higher:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  

  path_provider: ^2.1.1
  audioplayers: ^6.4.0
  shared_preferences: ^2.2.3

  # Notifications
  flutter_local_notifications: ^19.0.0

  # Location tracking & distance calculation
  geolocator: ^14.0.0

  # UPDATED VERSIONS
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.2

  battery_plus: ^7.0.0
  logging: ^1.0.2
  connectivity_plus: ^7.0.0
  flutter_dotenv: ^6.0.0
  
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  permission_handler: ^12.0.0
  app_settings: ^6.1.1
  device_info_plus: ^12.1.0

  # Google Maps & Places
  google_maps_flutter: ^2.2.5
  google_places_flutter: ^2.0.0

  # Ads & In-app purchases
  google_mobile_ads: ^6.0.0
  in_app_purchase: ^3.2.1

  cupertino_icons: ^1.0.8
  android_intent_plus: ^6.0.0
  package_info_plus: ^9.0.0

  # Fonts
  google_fonts: ^6.2.1

  # HTTP API calls
  http: ^1.4.0
  sensors_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.5
  flutter_launcher_icons: ^0.14.3
  meta: ^1.12.0 # ADDED DEPENDENCY

flutter:
  uses-material-design: true
  assets:
    - assets/geowake.png
    - assets/ringtones/

flutter_native_splash:
  color: "#FFFFFF" # Match this with your custom splash background
  image: assets/geowake.png
  android_12:
    image: assets/geowake.png
    icon_background_color: "#FFFFFF"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/geowake.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/geowake.png"
